trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: SingleStage
  dependsOn: []
  jobs:
  - job: "One"
    dependsOn: 'Two'
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'API'
        method: 'POST'
        body: |
          {
            "buildNumber": "$(build.buildId)",
            "isMultiBranch": "true",
            "branchName": "$(build.sourceBranchName)"
          }
        waitForCompletion: 'true'
    - task: Delay@1
      inputs:
        delayForMinutes: '0'
  - job: "Two"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Hello world ' 
- stage: Build
  dependsOn: []
  jobs:
  - job: 'Three'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Hello world'
  - job: 'Four'
    dependsOn: 'Three'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
