trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: SingleStage
  jobs:
  - job: "Two"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Hello world ' 
- stage: Build
  jobs:
  - job: 'Three'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Hello world'
  - job: 'Four'
    dependsOn: 'Three'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
